services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: server
    expose:
      - "8080"
    volumes:
      - ./uploads:/app/uploads
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8081:80"
      - "8443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/certs:/etc/nginx/certs:ro
    depends_on:
      - server